version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/fastapi-app

hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: scripts/install.sh
      timeout: 900
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ubuntu