# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/reference/configuration-reference
version: 2.1

executors:
  python-deploy:
    working_directory: ~/fastapi-app-code-deploy
    environment:
      AWS_CODE_DEPLOY_DEPLOYMENT_DESCRIPTION: "Deployed via CircleCI on $(date)"
    docker:
      # Specify the version you desire here
      # See: https://circleci.com/developer/images/image/cimg/base
      - image: cimg/base:2025.07

commands:
  install-aws-client:
    steps:
      - run:
          name: "Install AWS Client."
          command: |
            curl -sSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" > /tmp/awscliv2.zip
            unzip /tmp/awscliv2.zip -d /tmp/awscliv2
            sudo /tmp/awscliv2/aws/install  

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/guides/orchestrate/jobs-steps/#jobs-overview & https://circleci.com/docs/reference/configuration-reference/#jobs
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/guides/execution-managed/executor-intro/ & https://circleci.com/docs/reference/configuration-reference/#executor-job
    docker:
      # Specify the version you desire here
      # See: https://circleci.com/developer/images/image/cimg/base
      - image: cimg/base:2025.07

    # Add steps to the job
    # See: https://circleci.com/docs/guides/orchestrate/jobs-steps/#steps-overview & https://circleci.com/docs/reference/configuration-reference/#steps
    steps:
      # Checkout the code as the first step.
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
  lint:
    executor: "python-deploy"
    steps:
      - checkout
      - run:
          name: Install linters
          command: |
            sudo apt update && sudo apt install -y shellcheck gitlint
      - run:
          name: Validate Git Commits
          command: |
            gitlint --commits "origin/main...$CIRCLE_SHA1"
      - run:
          name: Shellcheck bash scripts
          command: |
            exec 1>&2
            for file in $(git diff --cached --name-only --diff-filter=ACM) ; do
              if file ${file} | grep "Bourne-Again shell script" ; then
                bash -n ${file} || exit $?
                shellcheck ${file} ||exit $?
              fi
            done
# Orchestrate jobs using workflows
# See: https://circleci.com/docs/guides/orchestrate/workflows/ & https://circleci.com/docs/reference/configuration-reference/#workflows
workflows:
  say-hello-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - say-hello
      - lint